#!/usr/bin/env python
"""Scheduled / on-demand daily run: build the meeting packet and email it as a PDF.

This is the ONE entry point the scheduler invokes and the same command you run by hand. It wraps the
existing, unchanged engine (calendar read -> per-meeting briefs -> packet markdown) and adds only a
delivery layer: render the packet to PDF and email it to a single recipient.

    python scheduled_run.py                 # today (Europe/Paris), email the PDF  (what cron runs)
    python scheduled_run.py --date 2026-06-29   # any day, on demand
    python scheduled_run.py --no-email          # build + save PDF locally, do NOT send
    python scheduled_run.py --to me@x.com       # one-off: override the recipient

Guarantees:
  * Headless: API-key model auth + Notion integration token + Google service account. No login.
  * Read-only everywhere except the email: the run ASSERTS zero writes to Notion and the calendar
    before sending; email is the only outbound action.
  * Never fails silently: on the emailing path, ANY failure (API/network/429-after-retries, calendar
    or render error, empty day, a detected write) sends a FAILURE notice with a short traceback and
    exits non-zero. With --no-email, the same failure is printed to the console and exits non-zero.

Exit codes: 0 success · 2 usage / missing credential (fail fast) · 1 any run failure.
"""

import argparse
import asyncio
import json
import os
import sys
import traceback
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from brief_agent.agent import DEFAULT_MODEL
from brief_agent.calendar import resolve_date
from brief_agent.config import (
    MissingAPIKeyError,
    MissingNotionTokenError,
    ensure_credentials,
)
from brief_agent.daily import build_day_packet, packet_provenance, render_packet
from brief_agent.heartbeat import heartbeat_url, ping
from brief_agent.mailer import (
    MissingSMTPConfigError,
    load_email_config,
    send_email,
    send_failure_notice,
)
from brief_agent.pdf import render_packet_pdf

_TZ = ZoneInfo("Europe/Paris")


class PacketError(RuntimeError):
    """A whole-run failure worth a FAILURE email (e.g. a write was detected). NOT per-meeting or
    empty-day: those ship in the packet."""


# --------------------------------------------------------------------------- #
# Packet building reuses the shared brief_agent.daily helpers (so the scheduled run and the
# --calendar CLI fetch/brief/provenance identically and cannot drift).
# --------------------------------------------------------------------------- #
def _save_outputs(out_dir: Path, day: date, md: str, pdf_bytes: bytes, provenance: dict) -> dict:
    """Write day-<ISO>.{md,pdf,sources.json}. Deterministic names → idempotent, safe to re-run."""
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"day-{day.isoformat()}"
    md_path = out_dir / f"{stem}.md"
    pdf_path = out_dir / f"{stem}.pdf"
    src_path = out_dir / f"{stem}.sources.json"
    md_path.write_text(md, encoding="utf-8")
    pdf_path.write_bytes(pdf_bytes)
    src_path.write_text(
        json.dumps(provenance, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return {"md": md_path, "pdf": pdf_path, "sources": src_path}


def _counts_line(packet) -> str:
    parts = [f"{packet.briefed} briefed", f"{packet.stubs} unresolved"]
    if packet.failed:
        parts.append(f"{packet.failed} could not complete")
    parts.append(f"{len(packet.skipped)} skipped (internal)")
    return f"{packet.total} meetings - " + " / ".join(parts)


def _email_body(packet, day: date, pdf_name: str) -> str:
    when = day.strftime("%A %d %B %Y")
    note = (
        "" if not packet.failed
        else "\nSome meetings could not be briefed (listed in the packet); the rest are included.\n"
    )
    return (
        f"Meeting briefs for {when} are attached ({pdf_name}).\n\n"
        f"{_counts_line(packet)}.\n{note}\n"
        "Read-only run: 0 writes to Notion and the calendar. Generated by the meeting-brief agent.\n"
    )


def _short_traceback(limit: int = 2000) -> str:
    tb = traceback.format_exc()
    return tb if len(tb) <= limit else "...\n" + tb[-limit:]


# --------------------------------------------------------------------------- #
# Run
# --------------------------------------------------------------------------- #
def _run(args) -> int:
    emailing = not args.no_email
    day = args.day  # already resolved + validated in main()
    out_dir = Path(args.out_dir)

    # On the emailing path, resolve SMTP config UP FRONT: fail fast if it's missing (we could not
    # send a failure notice anyway), and keep `cfg` ready for the failure path below.
    cfg = None
    if emailing:
        try:
            cfg = load_email_config(args.to)
        except MissingSMTPConfigError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2

    print(
        f"Building the meeting packet for {day.isoformat()} (Europe/Paris) using model "
        f"'{args.model}'{'' if args.no_web else ' (+ web news)'}…",
        file=sys.stderr,
    )

    try:
        packet = asyncio.run(build_day_packet(day, args.model, enable_web=not args.no_web))

        # Read-only gate: any write tool seen anywhere in the run is a hard failure (→ failure email).
        if packet.made_any_write:
            raise PacketError(
                f"write tool(s) were called — {sorted(set(packet.write_tool_calls))}"
            )
        # NOTE: an empty day is NOT a failure — it ships a normal "no external meetings" packet so a
        # quiet weekend doesn't trigger a scary FAILED alert. Per-meeting failures (packet.failed)
        # likewise ride along in the packet. Only a whole-run failure (above, or a raised calendar/
        # send error) escalates to the failure email.

        md = render_packet(packet)
        pdf_name = f"meeting-briefs-{day.isoformat()}.pdf"
        pdf_bytes = render_packet_pdf(md, title=f"Meeting briefs - {day.isoformat()}")
        paths = _save_outputs(out_dir, day, md, pdf_bytes, packet_provenance(packet, day, args.model))

        print(
            f"Packet: {_counts_line(packet)}. Saved {paths['pdf']} ({len(pdf_bytes)} bytes) "
            f"+ {paths['md'].name} + {paths['sources'].name}.",
            file=sys.stderr,
        )

        if emailing:
            subject = f"Meeting briefs — {day.strftime('%A %d %B %Y')}"
            send_email(cfg, subject, _email_body(packet, day, pdf_name), [(pdf_name, pdf_bytes)])
            print(f"Emailed PDF to {cfg.recipient} (subject: {subject!r}).", file=sys.stderr)
            # Dead-man's switch: ping the watchdog ONLY after a successful send. Best-effort.
            hb = heartbeat_url()
            if hb and ping(hb):
                print("Heartbeat pinged (run healthy).", file=sys.stderr)
        else:
            print("--no-email: saved locally, send skipped (no heartbeat).", file=sys.stderr)

        print("Writes: 0 to Notion and Calendar (read-only).", file=sys.stderr)
        return 0

    except Exception as exc:  # noqa: BLE001 - the whole run is wrapped so it never fails silently
        summary = f"{type(exc).__name__}: {exc}"
        short_tb = _short_traceback()
        print(f"error: {summary}", file=sys.stderr)

        if emailing and cfg is not None:
            subject = f"Meeting briefs — FAILED — {day.isoformat()}"
            try:
                send_failure_notice(cfg, subject, summary, short_tb)
                print(f"Sent failure notice to {cfg.recipient}.", file=sys.stderr)
            except Exception as mail_exc:  # noqa: BLE001
                print(
                    f"ALSO could not send the failure email: "
                    f"{type(mail_exc).__name__}: {mail_exc}",
                    file=sys.stderr,
                )
        else:
            # --no-email: no failure email; surface the traceback to the console.
            print(short_tb, file=sys.stderr)
        return 1


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="scheduled_run",
        description="Build the day's meeting packet and email it as a PDF (scheduled or on demand).",
    )
    p.add_argument("--date", default="today",
                   help="today (default) | tomorrow | YYYY-MM-DD. Resolved in Europe/Paris.")
    p.add_argument("--no-email", action="store_true",
                   help="Build + save the PDF locally; do not send. Errors go to the console.")
    p.add_argument("--to", default=None, help="Override the recipient for a one-off send.")
    p.add_argument("--no-web", action="store_true", help="Disable web enrichment (faster; for testing).")
    p.add_argument("--out-dir", default="out", help="Where to save the PDF/MD/sidecar (default: out/).")
    p.add_argument("--model", "-m", default=os.environ.get("BRIEF_AGENT_MODEL", DEFAULT_MODEL),
                   help='Model alias ("opus", "sonnet") or full ID (default: opus).')
    # --once is an intentional no-op alias: the default invocation already runs immediately. It
    # exists only so the documented "run it now to test" command reads naturally.
    p.add_argument("--once", action="store_true",
                   help="Run immediately (the default behaviour; accepted for the test command).")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    # Fail fast on missing model/CRM credentials (no fallback, no interactive login).
    try:
        ensure_credentials()
    except (MissingAPIKeyError, MissingNotionTokenError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    # Reuse the CLI's date resolver (today/tomorrow/YYYY-MM-DD); "today" is in Europe/Paris.
    try:
        args.day = resolve_date(args.date, today=datetime.now(_TZ).date())
    except ValueError:
        print(f"error: bad --date {args.date!r} (use today | tomorrow | YYYY-MM-DD).", file=sys.stderr)
        return 2

    return _run(args)


if __name__ == "__main__":
    raise SystemExit(main())
